
name: universal_stream_player
description: "A music player that integrates all your streaming songbook into a single app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Autenticação e Rede ---
  http: ^1.2.0
  flutter_web_auth_2: ^3.1.2
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0

  # --- Gerenciamento de Estado e Dados ---
  provider: ^6.1.2
  shared_preferences: ^2.2.2

  # --- UI e Utilitários ---
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env

