name: universal_stream_player
description: "A music player that integrates all your streaming songbook into a single app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Ícones
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  audio_video_progress_bar: ^2.0.1

  # Redes e Autenticação
  http: ^1.2.0
  flutter_web_auth_2: ^4.1.0
  crypto: ^3.0.3
  url_launcher: ^6.2.1

  # Persistência e Configuração
  shared_preferences: ^2.2.2
  flutter_dotenv: ^6.0.0

  # Player de Áudio
  just_audio: ^0.10.5

  # Fonte de Áudio
  youtube_explode_dart: ^3.0.5

  # Database support added earlier
  sqflite: ^2.2.8
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
